### ISSUE TITLE
Return exception message instead of "Internal server error"

### ISSUE THREAD

**Issue by gondik** [tomaj/nette-api#36]
Would be cool if the **ApiPresenter** will return the error response message based on the catched Exception instead of the general "Internal server error".

https://github.com/tomaj/nette-api/blob/master/src/Presenters/ApiPresenter.php#L93

`$response = new JsonApiResponse(500, ['status' => 'error', 'message' => 'Internal server error']);`

to 

`$response = new JsonApiResponse(500, ['status' => 'error', 'message' => $exception->getMessage()]);`

**Comment by lulco** [comment]
I think this is already fixed with detail parameter if Debugger::isEnabled() returns true
