### ISSUE TITLE
BearerTokenAuthorization cannot authorize - HTTP_AUTHORIZATION empty in $_SERVER on CGI/fastCGI

### ISSUE THREAD

**Issue by zemnet** [tomaj/nette-api#37]
This is not issue, but maybe will help for others.
BearerTokenAuthorization not work on api requests and on Test presenter too.

If your apache server is runing on CGI or fastCGI script, $_SERVER['HTTP_AUTHORIZATION'] is empty.

You'll need to do some mod_rewrite wizardry to get your headers past the CGI barrier, like so:

> RewriteEngine on
> RewriteRule .? - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`

[https://stackoverflow.com/questions/827060/how-can-i-access-request-headers-that-dont-appear-in-server](url)

**Comment by tomaj** [comment]
Hi.

Thanks for info. This is something that need to be done in web server, not in library. I will put your example to README because it could be useful for others.
