### ISSUE TITLE
Logger Exception

### ISSUE THREAD

**Issue by martinjinda** [tomaj/nette-api#40]
The logging works automatically just by registering to config.neon? I am getting this error.

`Interface Tomaj\NetteApi\Logger\ApiLoggerInterface used in service '32_Tomaj_NetteApi_Logger_ApiLoggerInterface' must have just one non-static method create() or get().`

Thanks.

**Comment by tomaj** [comment]
you have to provide implementation of `ApiLoggerInterface` in config neon an it should be ok

**Comment by martinjinda** [comment]
Same problem.

**Comment by tomaj** [comment]
can you provide more informations? right now i added this package with logging to new project and everything worked.

**Comment by martinjinda** [comment]
could you please give me a small example of it?
