### ISSUE TITLE
ConsoleResponse::getResponseHeaders might return null

### ISSUE THREAD

**Issue by rootpd** [tomaj/nette-api#74]
The definition of function is enforcing `string` return type:

```php
public function getResponseHeaders(): string
{
    return $this->responseHeaders;
}
```

But if the request ends up with connection refused error (or possibly any related kind of error), the headers are `null` and type checking causes an error:

![image](https://user-images.githubusercontent.com/812909/77425659-5af8c000-6dd3-11ea-9764-c131d302a79c.png)

![image](https://user-images.githubusercontent.com/812909/77425768-89769b00-6dd3-11ea-9bd6-82f767da9287.png)

**Comment by lulco** [comment]
is it version 2.0.0?

**Comment by rootpd** [comment]
Yep

**Comment by lulco** [comment]
can you check with `dev-typehint-fixes as 2.0.1`?

**Comment by rootpd** [comment]
all good now :+1:

**Comment by lulco** [comment]
ok we will merge it and release new version soon

**Comment by lulco** [comment]
version 2.0.1 is out
