### ISSUE TITLE
Rate Limiter

### ISSUE THREAD

**Issue by stolfam** [tomaj/nette-api#92]
Jak může fungovat RateLimiter, kdyz pro něj funkce vubec nemá parametr? Viz, fce addApi()
https://github.com/tomaj/nette-api/blob/master/src/ApiDecider.php#L68

Marně si lámu hlavu proč to nefunguje a pak sem přišel na to, že funkce addApi parametr ignoruje. Nebo se pletu a nastavuju neco blbe?

Díky moc za případné vysvětlení!

**Comment by lulco** [comment]
Dik za report! 
Je to tak O:-) Fix v dev-rate-limit-fix https://github.com/tomaj/nette-api/pull/93
Checkni pls a ak vsetko bude ok, mozeme mergnut a vydat novu verziu.

**Comment by stolfam** [comment]
Perfektní! Tohle funguje! Díky moc!

**Comment by lulco** [comment]
super, mergol som to do mastra, verzia bude coskoro
